//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smop.MainApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindow_IsMaximized {
            get {
                return ((bool)(this["MainWindow_IsMaximized"]));
            }
            set {
                this["MainWindow_IsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_Width {
            get {
                return ((double)(this["MainWindow_Width"]));
            }
            set {
                this["MainWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_Height {
            get {
                return ((double)(this["MainWindow_Height"]));
            }
            set {
                this["MainWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_X {
            get {
                return ((double)(this["MainWindow_X"]));
            }
            set {
                this["MainWindow_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MainWindow_Y {
            get {
                return ((double)(this["MainWindow_Y"]));
            }
            set {
                this["MainWindow_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Logger_Folder {
            get {
                return ((string)(this["Logger_Folder"]));
            }
            set {
                this["Logger_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double App_ZoomLevel {
            get {
                return ((double)(this["App_ZoomLevel"]));
            }
            set {
                this["App_ZoomLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Comm_OdorDisplay_Port {
            get {
                return ((string)(this["Comm_OdorDisplay_Port"]));
            }
            set {
                this["Comm_OdorDisplay_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Comm_SmellInsp_Port {
            get {
                return ((string)(this["Comm_SmellInsp_Port"]));
            }
            set {
                this["Comm_SmellInsp_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Assets/ion-vision/default.json")]
        public string Comm_IonVision_SetupFilename {
            get {
                return ((string)(this["Comm_IonVision_SetupFilename"]));
            }
            set {
                this["Comm_IonVision_SetupFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Pulses_SetupFilename {
            get {
                return ((string)(this["Pulses_SetupFilename"]));
            }
            set {
                this["Pulses_SetupFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pulses_Randomize {
            get {
                return ((bool)(this["Pulses_Randomize"]));
            }
            set {
                this["Pulses_Randomize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Comm_IonVision_IgnoreVersionWarning {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Comm_IonVision_IgnoreVersionWarning"]));
            }
            set {
                this["Comm_IonVision_IgnoreVersionWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float Reproduction_ML_Threshold {
            get {
                return ((float)(this["Reproduction_ML_Threshold"]));
            }
            set {
                this["Reproduction_ML_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Reproduction_ML_MaxIterations {
            get {
                return ((int)(this["Reproduction_ML_MaxIterations"]));
            }
            set {
                this["Reproduction_ML_MaxIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Reproduction_Odors {
            get {
                return ((string)(this["Reproduction_Odors"]));
            }
            set {
                this["Reproduction_Odors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Reproduction_UsePID {
            get {
                return ((bool)(this["Reproduction_UsePID"]));
            }
            set {
                this["Reproduction_UsePID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float Reproduction_SniffingDelay {
            get {
                return ((float)(this["Reproduction_SniffingDelay"]));
            }
            set {
                this["Reproduction_SniffingDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public float Reproduction_Humidity {
            get {
                return ((float)(this["Reproduction_Humidity"]));
            }
            set {
                this["Reproduction_Humidity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reproduction_UseDmsCache {
            get {
                return ((bool)(this["Reproduction_UseDmsCache"]));
            }
            set {
                this["Reproduction_UseDmsCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Reproduction_ML_Algorithm {
            get {
                return ((string)(this["Reproduction_ML_Algorithm"]));
            }
            set {
                this["Reproduction_ML_Algorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Reproduction_ML_CmdParams {
            get {
                return ((string)(this["Reproduction_ML_CmdParams"]));
            }
            set {
                this["Reproduction_ML_CmdParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Reproduction_SntSampleCount {
            get {
                return ((int)(this["Reproduction_SntSampleCount"]));
            }
            set {
                this["Reproduction_SntSampleCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Reproduction_DmsSingleSV {
            get {
                return ((float)(this["Reproduction_DmsSingleSV"]));
            }
            set {
                this["Reproduction_DmsSingleSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setup_ShowThermistors {
            get {
                return ((bool)(this["Setup_ShowThermistors"]));
            }
            set {
                this["Setup_ShowThermistors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setup_ShowMonometers {
            get {
                return ((bool)(this["Setup_ShowMonometers"]));
            }
            set {
                this["Setup_ShowMonometers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double PulseEditor_Height {
            get {
                return ((double)(this["PulseEditor_Height"]));
            }
            set {
                this["PulseEditor_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public float Pulses_Humidity {
            get {
                return ((float)(this["Pulses_Humidity"]));
            }
            set {
                this["Pulses_Humidity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setup_HumidityAutoAdjustment {
            get {
                return ((bool)(this["Setup_HumidityAutoAdjustment"]));
            }
            set {
                this["Setup_HumidityAutoAdjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnownOdors {
            get {
                return ((string)(this["KnownOdors"]));
            }
            set {
                this["KnownOdors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.052")]
        public double Odor_BasePID {
            get {
                return ((double)(this["Odor_BasePID"]));
            }
            set {
                this["Odor_BasePID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.5")]
        public double Odor_BasePIDTemp {
            get {
                return ((double)(this["Odor_BasePIDTemp"]));
            }
            set {
                this["Odor_BasePIDTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.3")]
        public double Odor_PIDTempCompPower {
            get {
                return ((double)(this["Odor_PIDTempCompPower"]));
            }
            set {
                this["Odor_PIDTempCompPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.014")]
        public double Odor_PIDTempCompGain {
            get {
                return ((double)(this["Odor_PIDTempCompGain"]));
            }
            set {
                this["Odor_PIDTempCompGain"] = value;
            }
        }
    }
}
